steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - test_function
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=python37
      - --allow-unauthenticated